### PR TITLE
FAQ - How to deploy a Weld application to a Jetty standalone instance

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by jharting** [comment]
Merged and deployed, thanks!

**Comment by mkouba** [comment]
Don't merge it yet pls. It seems that we have one more problem with servlet component injection...

**Comment by mkouba** [comment]
@jharting It should be ok - false alarm.

**Comment by mkouba** [comment]
I will add one more update - it seems the cdi/weld module was added somewhere between 9.2.2 and  9.2.11 ... so using this module should be the preferred way.

**Comment by jharting** [comment]
Merged and deployed.

**Pull request closed without merging**
